version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearchhost
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elasticsearchnet
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearchhost:9200
    networks:
      - elasticsearchnet
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  elasticsearchnet:
    driver: bridge
