version: "3"
services:
 logstash:
    image: "mysql:5.5"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
    volumes:
      - "logstash_data:/data"

volumes:
 logstash_data:
