version: "3"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    restart: always
    hostname: mssql
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data # thư mục lưu DB
      - ./bk:/var/opt/mssql/backup # thư  mục chứa file backup
    environment:
      SA_PASSWORD: sa #Thiết lập password
      ACCEPT_EULA: Y

volumes:
  mssql_data:
