version: "3"
services:
  mysql:
    image: "mysql:5.5"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
    volumes:
      - "mysql_data:/data"

volumes:
  mysql_data:
