version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
  payload:
    image: node:18
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload

volumes:
  mongo_data:
