version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_START_RPC: "true"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_network

volumes:
  cassandra_data:

networks:
  cassandra_network: