version: "3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.11.0"
    restart: "always"
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch_data:/data"
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme   # đặt mật khẩu cho user "elastic"
    networks:
      - elasticsearch_net

volumes:
  elasticsearch_data:

networks:
  elasticsearch_net:
    driver: bridge
