version: "3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:9.1.4"
    restart: "always"
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme   # đặt mật khẩu cho user "elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elasticsearch_net

volumes:
  elasticsearch_data:

networks:
  elasticsearch_net:
    driver: bridge
