
version: "3"
services:
  db:
    image: mysql:8.0.30
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    # Tăng memory và CPU limits
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
volumes:
  db:
    driver: local