version: "3"
services:
  mongo:
    image: "mongo"
    command: --wiredTigerCacheSizeGB 0.25 --replSet s0
    restart: "always"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
