version: "3.9"

services:
  scylladb:
    image: scylladb/scylla:2025.1
    container_name: scylladb
    restart: always
    ports:
      - "9042:9042" # CQL port for ScyllaDB
      - "9180:9180" # Alternator (DynamoDB-compatible) API
    volumes:
      - scylla_data:/var/lib/scylla
    environment:
      - SCYLLA_ENVIRONMENT=production

volumes:
  scylla_data: